kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume1
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/c/Users/kondaveetih/web-log"